グラン・エプレの追加
fvh-P/assaultlily-rdf pull request #2
Opened 2021-03-18 08:33 UTC by miyacorata

2021-03-18 15:48 UTC, fvh-P reviewed
こちらで直しましたが、一応。

2021-03-18 15:48 UTC, miyacorata commented
いつのまにか仕事が消えてた

2021-03-18 16:04 UTC, fvh-P requested changes
検討すべき事項

- ルームメイト
  叶星と高嶺はルームメイト？
- 過去のガーデンについて
    転校ではなく中学から高校への進学時にガーデンを移ったリリィは、`lily:pastGarden` に中学校名を書くべきか
- 神庭女子の学科名がこれで正しいかどうか自信があまりない
  - 音楽科？声楽科？
    ラスバレのイベントストーリー（カラフルダイアリー1話-1）で定盛が自身の学科について「声楽科」と言っている。
    いくつかの非公式サイトでは音楽科と書かれているが情報源が不明。
  - 美術科？絵画科？
    ラスバレのイベントストーリー（カラフルダイアリー1話-4）で高嶺が灯莉の学科について「美術科だったわよね？」と言っており、灯莉は「そーだよ！」と返している。
    二水ちゃんは神庭女子で入りたい学科について「絵画科？」と言っている。(https://twitter.com/assault_lily/status/1363141951453753353?s=20)

2021-03-18 16:09 UTC, miyacorata commented
叶星様と高嶺様がルームメイトかどうか、それこそふみちゃんに聞くべき案件では

2021-03-19 05:53 UTC, fvh-P submitted a review, later dismissed
検討した結果
- 叶星と高嶺はルームメイトっぽいが、保留
  カラフルダイアリー1-5で叶星が1年生に向かって「私**たち**の部屋」と言ってる。状況証拠はある。
  コメントアウト状態で保留とする。
- `lily:pastGarden` は現時点ではやらない。泥沼が見えるので。
- 学科名問題
  落としどころとして、音楽科（声楽）、美術科（絵画）という独自表記を採用。

2021-03-19 06:01 UTC, fvh-P approved these changes
検討した結果
- 叶星と高嶺はルームメイトっぽいが、保留
  カラフルダイアリー1-5で叶星が1年生に向かって「私**たち**の部屋」と言ってる。状況証拠はある。
  コメントアウト状態で保留とする。
- `lily:pastGarden` は現時点ではやらない。泥沼が見えるので。
- 学科名問題
  落としどころとして、音楽科（声楽）、美術科（絵画）という独自表記を採用。

2021-03-19 06:02 UTC, merged