LGエイルのメンバーを追加
fvh-P/assaultlily-rdf pull request #29
Opened 2021-05-06 14:03 UTC by nixets

2021-05-06 14:54 UTC, fvh-P commented
#22 をマージしたので最新の master に rebase してコンフリクトを解消しつつ、ついでにキャスト情報のところを

```rdf
  <!-- <lily:cast rdf:parseType="Resource"> -->
    <!-- <schema:name xml:lang="ja"></schema:name> -->
    <!-- <lily:resource rdf:resource=""/> -->
    <!-- <lily:performIn rdf:resource=""/> -->
  <!-- </lily:cast> -->
```

このように書き換えてください。お願いします。

2021-05-07 04:11 UTC, fvh-P requested changes
ちょっと色々確認お願いします。

2021-05-07 04:11 UTC, fvh-P commented on RDFs/lily_yurigaoka.rdf
>    <rdf:type rdf:resource="https://lily.fvhp.net/rdf/IRIs/lily_schema.ttl#Lily"/>
明石愛華のキャストが水瀬いのりのままになっています。

2021-05-07 04:11 UTC, fvh-P commented on RDFs/lily_yurigaoka.rdf
> +<rdf:Description rdf:about="Takasaki_Sumire">
高崎遥礼さんのデータが2つあります。

2021-05-07 04:11 UTC, fvh-P commented on RDFs/lily_yurigaoka.rdf
> +  </lily:relationship>
これ合ってますか？

2021-05-07 04:11 UTC, fvh-P commented on RDFs/lily_yurigaoka.rdf
> +  <lily:castResource rdf:resource="http://ja.dbpedia.org/resource/水瀬いのり"/>
```suggestion
  <lily:cast rdf:parseType="Resource">
    <schema:name xml:lang="ja">水瀬いのり</schema:name>
    <lily:resource rdf:resource="https://www.wikidata.org/wiki/Q11548933"/>
    <lily:resource rdf:resource="http://ja.dbpedia.org/resource/水瀬いのり"/>
    <lily:performIn rdf:resource="Assault_Lily_Bouquet"/>
    <lily:performIn rdf:resource="Assault_Lily_Last_Bullet"/>
  </lily:cast>
```

2021-05-07 07:16 UTC, nixets commented on RDFs/lily_yurigaoka.rdf
> +  </lily:relationship>
明石愛華のデータが混じっていました。リベースマージの時に、並び替えると一部ブロックのみだけ交換したような表記になることがあり、それが原因のようです

2021-05-07 09:53 UTC, nixets commented
制約に違反しているらしい。
lintのエラーが初見なのでちょっと確認お願いできますか。

2021-05-07 10:18 UTC, miyacorata requested changes

2021-05-07 10:18 UTC, miyacorata commented on RDFs/lily_yurigaoka.rdf
> -  <rdf:type rdf:resource="https://lily.fvhp.net/rdf/IRIs/lily_schema.ttl#Lily"/>
### `rdf:type` の宣言が消えています
`lilyrdf:Mashima_Moyu` が `lily:Lily` のインスタンスでなくなっているため制約違反が発生します

2021-05-07 10:23 UTC, fvh-P commented on RDFs/lily_yurigaoka.rdf
> +</rdf:Description>
lintの出力を見ると、
```
WARN  SHACL violation: "Value must be an instance of <https://lily.fvhp.net/rdf/IRIs/lily_schema.ttl#Lily>" (http://www.w3.org/ns/shacl#ClassConstraintComponent)
(line: 888, col: 1, triple: https://lily.fvhp.net/rdf/RDFs/detail/Miliam_Hildegard_von_Guropius - https://lily.fvhp.net/rdf/IRIs/lily_schema.ttl#schutzengel - https://lily.fvhp.net/rdf/RDFs/detail/Mashima_Moyu)
```
と言われています。これは、

- value が `lily:Lily` の type を持っていないといけません。
- その value というのは 888 行目のこのトリプルの value です。

ということです。ここで「このトリプルの value」とは、`-` で区切られたうち3つ目の `https://lily.fvhp.net/rdf/RDFs/detail/Mashima_Moyu` のことです。

つまり、百由のデータの type がおかしいということです。

百由のデータを見てみると、編集の過程でここにあった
```rdf
  <rdf:type rdf:resource="https://lily.fvhp.net/rdf/IRIs/lily_schema.ttl#Lily"/>
```

が消されてしまっていて type の指定がありません。これが原因のようです。

シュッツエンゲル関係やその他関係の対象は `lily:Lily` のエンティティに限定するという制約があるので、この型指定がないとlintで怒られます。

2021-05-07 12:52 UTC, miyacorata approved these changes

2021-05-07 12:53 UTC, merged