リリィのデータをXML形式からTurtle形式に変更
fvh-P/assaultlily-rdf pull request #61
Opened 2021-11-25 17:09 UTC by fvh-P

a part of #57 

### チェック項目

この変更は
- [ ] 新しいクラスやプロパティ定義を追加する
- [ ] 既存のデータ構造やデータ規則の破壊的な変更を含む
- [ ] 既存のRDF制約に違反しており、制約を緩和する必要がある

@miyacorata 
XML -> Turtle の過程で消失してるpredicateがないかだけ確認してもらえると助かります。

2021-11-26 00:13 UTC, fvh-P reviewed
nameKana 消えてんじゃん

2021-11-26 00:29 UTC, miyacorata commented
バチクソ深刻で草(今日退勤してから確認します)

2021-11-27 10:27 UTC, miyacorata requested changes
## 修正すべき点
* 複数のレギオン役職を持つリリィのレギオン役職が一つのみになっています
  * 工藤朔愛、吉原菜乃葉、立原紗癒、相澤一葉、川村楪、月岡椛などが該当します
* エレンスゲ女学院所属のリリィの序列データが欠落しています

## 些細な点
* `lily_erensuge.ttl` はこの機会に `lily_herensuge.ttl` にリネームしても良さそうな気配がします

2021-11-27 12:13 UTC, miyacorata approved these changes
お疲れさまでした！

![ゆりあさま(Quarter)](https://user-images.githubusercontent.com/12165058/143680864-871ac297-9f57-461a-871b-877a6221fbca.jpg)

2021-11-27 14:56 UTC, merged